### ISSUE TITLE
h value for very high resolution?

### ISSUE THREAD

**Issue by sckinta** [tmlagler/hicACT#3]
Hi I have a question about h smoothing value, from the table given at github and paper, authors only specified h value for resolution >= 5 kb. What if resolution=1kb, 2kb and 4kb?

From the check_input code, I found that hicACT allowed 1 ~ 4 kb resolution input. Could you also provide h value for 1~4kb resolution in table too? 

```
if (kb %in% 1:4 & (h >= 60 | h <= 25)) {
            if (ignore_warnings == F) {
                stop("Smoothing window (h) may not be of appropriate size for specified data resolution. To proceed, specify 'ignore_warnings=T' as function parameter")
            }
            else {
                warning("Smoothing window (h) may not be of appropriate size for specified data resolution")
            }
        }
```

so far I choose 1kb ~ h = 200, 2kb ~ h=100, 4kb~ h=50. Is that appropriate? Why cannot h be higher than 60?

**Comment by sckinta** [comment]
One additional comments about check_input() function. I would suggest to change the below the code to include 0 as fragment identifiers. Limiting positive integers reports error when user provide 0-based bedpe file as input. From what I understand, including 0 does not affect the algorithm run at all. It is just a identifier. 

```
if (any(indata[, eval(bin1)]%%1 != 0) > 0 | any(indata[, 
        eval(bin1)] <= 0)) {
        stop("Fragment identifiers must be positive integers")
    }
    if (any(indata[, eval(bin2)]%%1 != 0) > 0 | any(indata[, 
        eval(bin2)] <= 0)) {
        stop("Fragment identifiers must be positive integers")
    }
```

**Comment by tmlagler** [comment]
I think h=50 would be appropriate for 4kb data. I am not sure about the smoothing parameter for 1-2kb data; it is an area we are interested in exploring in the future, but have not done so yet. It seems reasonable to proportionally increase h with increasing data resolution, but there may be diminishing returns with such a large smoothing window. However, due to the Gaussian weights, the results should be relatively insensitive to small changes in the choice of h (e.g., h=200 or 150 for 1kb data). In short, h can be greater than 60 (set ignore_warnings=T).

Thank you for the suggestion! I have modified the code to allow for any integer, including 0.

**Comment by sckinta** [comment]
Thanks for the quick answer! Closed the issue.
